name: JS build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y \
            gettext autopoint valac
          pip install -r requirements.txt
          rustup target add wasm32-unknown-emscripten
          cargo install cbindgen

      - name: Get emscripten version
        run: |
          echo "EMSCRIPTEN_VERSION=$(cat .emscripten-version)" >> $GITHUB_ENV

      - name: Setup emsdk
        uses: emscripten-core/setup-emsdk@v16
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}

      - name: Version info
        run: |
          bison --version
          cmake --version
          valac --version
          rustc --version

      - name: Build
        run: |
          python scripts/build.py js

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: artifact-js
          path: |
            build/js/*.tar.bz2

      - name: Check absolute path
        run: ./scripts/check-absolute-path.sh

      - name: Release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.ref == 'refs/heads/master' && 'js' || 'js-testing' }}
          prerelease: true
          title: ${{ github.ref == 'refs/heads/master' && 'JS Build' || 'JS Testing Build' }}
          files: |
            build/js/*.tar.bz2

      - name: Delete js-testing release
        if: ${{ github.ref == 'refs/heads/master' }}
        run: gh release delete js-testing -y || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  compare:
    needs: build
    if: ${{ github.ref != 'refs/heads/master' }}
    uses: ./.github/workflows/compare.yml
    with:
      platform: js
